function energy = compute_energy_lost(current_data, prev_data, const)
    energy = const.ht/2*(const.kappa_th*(prev_data.phi'*const.Kd(2:end, 2:end) ...
        *prev_data.phi + current_data.phi'*const.Kd(2:end, 2:end)*current_data.phi) ...
        - const.zeta_d*(prev_data.phi'*const.Md(2:end, 2:end)*prev_data.phi ...
        + current_data.phi'*const.Md(2:end, 2:end)*current_data.phi) ...
        + const.alpha_d*(prev_data.ut'*const.Kd*prev_data.ut ...
        + current_data.ut'*const.Kd*current_data.ut) ...
        + K(prev_data.r)*prev_data.phi(end) + K(current_data.r) ...
        *current_data.phi(end) + const.alpha_b*(prev_data.wt'*const.Kb ...
        *prev_data.wt + current_data.wt'*const.Kb*current_data.wt ...
        + prev_data.theta_t'*const.Kb*prev_data.theta_t + current_data.theta_t' ...
        *const.Kb*current_data.theta_t));