function energy = current_energy(data, const)
    e_d = 1/2*(data.ut'*const.Md*data.ut + const.Ed*data.u'*const.Kd*data.u ...
        + data.phi'*const.Md(2:end, 2:end)*data.phi);
    
    e_b = 1/2*(data.wt'*const.Mb*data.wt + const.Eb*data.theta'*const.Kb*data.theta ...
        + const.G*(-2*data.w'*const.Sb*data.theta + data.w'*const.Kb*data.w) ...
        + data.theta_t'*const.Mb*data.theta_t) ...
        + 1/2*(const.beta + const.rho/2*data.w'*const.Kb*data.w) ...
        *data.w'*const.Kb*data.w;
    
    energy = e_d + e_b;
    